import '@/styles/globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
import VisualEditor from '@/components/NodeHive/VisualEditor';

export const metadata = {
  title: 'Create nn-nextjs-starter',
  description: 'Generated by nn-nextjs-starter',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
        <VisualEditor />
      </body>
    </html>
  );
}
